export const femaleHair = [
    'Close Shave',
    'Short Bob',
    'Bob',
    'Pigtails',
    'Ponytail',
    'Braided Mohawk',
    'Braids',
    'Bob',
    'Faux Hawk',
    'French Twist',
    'Long Bob',
    'Loose Tied Ponytail',
    'Pixie',
    'Side Parted Shaved Bangs',
    'Top Knot',
    'Wavy Long',
    'Messy Tied Bandana',
    'Messy Bun with Cropped Bangs',
    'Bob with Feathers',
    'Tight Bun Cropped Bangs',
    'Frizzy Curly Afro',
    'Messy Wavy Bangs',
    'Tight Top Bun Braided',
    'Mullet',
    'Night Vision',
    'Braided Corn Rows',
    'Center Part Braided Corn Rows',
    'Diamond Corn Rows',
    'Pigtails with Bangs',
    'Star Braided Corn Rows',
    'Vertical Shaved Corn Rows',
    'Loose Tied Ponytail',
    'Short Mullet',
    'Shaved Sides Slicked Back',
    'Side Parted Shaved Bangs',
    'Mohawk',
    'Tied Pigtails with Bandana',
    'The Karen',
    'Center Parted Bob',
    'Pixie',
    'Bob',
    'Pigtails',
    'Loose Tied Ponytail',
    'Braided Mohawk',
    'Braids',
    'Straight Bob',
    'Faux Hawk',
    'French Twist',
    'Long Bob',
    'Ponytail Bun',
    'Pixie',
    'Side Parted Shaved Bangs',
    'Top Knot',
    'Wavy Long',
    'Messy Tied Bandana',
    'Messy Top Knot with Bangs',
    'Bob with Feathers',
    'Tight Bun Cropped Bangs',
    'Frizzy Curly Afro',
    'Messy Wavy Bangs',
    'Tight Top Bun Braided',
    'Mullet',
    'Corn Rows',
    'Center Parted Corn Rows',
    'Diamond Corn Rows',
    'Pigtails',
    'Star Braided Corn Rows',
    'Vertical Shaved Corn Rows',
    'Loosely Tied Ponytail',
    'Short Mullet',
    'Shaved Sides Slicked Back',
    'Side Parted Shaved Bangs',
    'Mohawk',
    'Tied Pigtails with Bandana',
    'The Karen',
    'Pixie Bob',
    'Tight Pony Tail Bun',
    'Pixie Cut',
    'Elvis',
];
