import { THaircut } from '../model/types/THaircut.ts';
import MockImg from '../assets/female/0.jpg';

export const femaleHair: THaircut[] = [
    { img: MockImg, label: 'Close Shave' },
    { img: MockImg, label: 'Short Bob' },
    { img: MockImg, label: 'Bob' },
    { img: MockImg, label: 'Pigtails' },
    { img: MockImg, label: 'Ponytail' },
    { img: MockImg, label: 'Braided Mohawk' },
    { img: MockImg, label: 'Braids' },
    { img: MockImg, label: 'Bob' },
    { img: MockImg, label: 'Faux Hawk' },
    { img: MockImg, label: 'French Twist' },
    { img: MockImg, label: 'Long Bob' },
    { img: MockImg, label: 'Loose Tied Ponytail' },
    { img: MockImg, label: 'Pixie' },
    { img: MockImg, label: 'Side Parted Shaved Bangs' },
    { img: MockImg, label: 'Top Knot' },
    { img: MockImg, label: 'Wavy Long' },
    { img: MockImg, label: 'Messy Tied Bandana' },
    { img: MockImg, label: 'Messy Bun with Cropped Bangs' },
    { img: MockImg, label: 'Bob with Feathers' },
    { img: MockImg, label: 'Tight Bun Cropped Bangs' },
    { img: MockImg, label: 'Frizzy Curly Afro' },
    { img: MockImg, label: 'Messy Wavy Bangs' },
    { img: MockImg, label: 'Tight Top Bun Braided' },
    { img: MockImg, label: 'Mullet' },
    { img: MockImg, label: 'Night Vision' },
    { img: MockImg, label: 'Braided Corn Rows' },
    { img: MockImg, label: 'Center Part Braided Corn Rows' },
    { img: MockImg, label: 'Diamond Corn Rows' },
    { img: MockImg, label: 'Pigtails with Bangs' },
    { img: MockImg, label: 'Star Braided Corn Rows' },
    { img: MockImg, label: 'Vertical Shaved Corn Rows' },
    { img: MockImg, label: 'Loose Tied Ponytail' },
    { img: MockImg, label: 'Short Mullet' },
    { img: MockImg, label: 'Shaved Sides Slicked Back' },
    { img: MockImg, label: 'Side Parted Shaved Bangs' },
    { img: MockImg, label: 'Mohawk' },
    { img: MockImg, label: 'Tied Pigtails with Bandana' },
    { img: MockImg, label: 'The Karen' },
    { img: MockImg, label: 'Center Parted Bob' },
    { img: MockImg, label: 'Pixie' },
    { img: MockImg, label: 'Bob' },
    { img: MockImg, label: 'Pigtails' },
    { img: MockImg, label: 'Loose Tied Ponytail' },
    { img: MockImg, label: 'Braided Mohawk' },
    { img: MockImg, label: 'Braids' },
    { img: MockImg, label: 'Straight Bob' },
    { img: MockImg, label: 'Faux Hawk' },
    { img: MockImg, label: 'French Twist' },
    { img: MockImg, label: 'Long Bob' },
    { img: MockImg, label: 'Ponytail Bun' },
    { img: MockImg, label: 'Pixie' },
    { img: MockImg, label: 'Side Parted Shaved Bangs' },
    { img: MockImg, label: 'Top Knot' },
    { img: MockImg, label: 'Wavy Long' },
    { img: MockImg, label: 'Messy Tied Bandana' },
    { img: MockImg, label: 'Messy Top Knot with Bangs' },
    { img: MockImg, label: 'Bob with Feathers' },
    { img: MockImg, label: 'Tight Bun Cropped Bangs' },
    { img: MockImg, label: 'Frizzy Curly Afro' },
    { img: MockImg, label: 'Messy Wavy Bangs' },
    { img: MockImg, label: 'Tight Top Bun Braided' },
    { img: MockImg, label: 'Mullet' },
    { img: MockImg, label: 'Corn Rows' },
    { img: MockImg, label: 'Center Parted Corn Rows' },
    { img: MockImg, label: 'Diamond Corn Rows' },
    { img: MockImg, label: 'Pigtails' },
    { img: MockImg, label: 'Star Braided Corn Rows' },
    { img: MockImg, label: 'Vertical Shaved Corn Rows' },
    { img: MockImg, label: 'Loosely Tied Ponytail' },
    { img: MockImg, label: 'Short Mullet' },
    { img: MockImg, label: 'Shaved Sides Slicked Back' },
    { img: MockImg, label: 'Side Parted Shaved Bangs' },
    { img: MockImg, label: 'Mohawk' },
    { img: MockImg, label: 'Tied Pigtails with Bandana' },
    { img: MockImg, label: 'The Karen' },
    { img: MockImg, label: 'Pixie Bob' },
    { img: MockImg, label: 'Tight Pony Tail Bun' },
    { img: MockImg, label: 'Pixie Cut' },
    { img: MockImg, label: 'Elvis' },
];
