import { THaircut } from '../model/types/THaircut.ts';
import MockImg from '../assets/male/0.jpg';

export const maleHair: THaircut[] = [
    { img: MockImg, label: 'Close Shave' },
    { img: MockImg, label: 'Buzzcut' },
    { img: MockImg, label: 'Faux Hawk' },
    { img: MockImg, label: 'Shaved Sides Slicked Back' },
    { img: MockImg, label: 'Raised Front Same Length' },
    { img: MockImg, label: 'Col De Sacs and Long Back' },
    { img: MockImg, label: 'Close Shave and Loose Mohawk' },
    { img: MockImg, label: 'Ponytail' },
    { img: MockImg, label: 'Corn Rows' },
    { img: MockImg, label: 'Slicked Back Curly Back' },
    { img: MockImg, label: 'Slicked Back' },
    { img: MockImg, label: 'Spiked' },
    { img: MockImg, label: 'Short Bowl Cut' },
    { img: MockImg, label: 'Messy Long Length' },
    { img: MockImg, label: 'Dreads' },
    { img: MockImg, label: 'Straight Long Length' },
    { img: MockImg, label: 'Curly Long' },
    { img: MockImg, label: 'Straight Long Partial Messy' },
    { img: MockImg, label: 'Side Part Front Short' },
    { img: MockImg, label: 'Slicked Back Short' },
    { img: MockImg, label: 'Side Part Front Long' },
    { img: MockImg, label: 'Razer Side Part Slick' },
    { img: MockImg, label: 'Mullet' },
    { img: MockImg, label: 'Nightvision' },
    { img: MockImg, label: 'Corn Rows' },
    { img: MockImg, label: 'Starfish Corn Rows' },
    { img: MockImg, label: 'Zig Zag Corn Rows' },
    { img: MockImg, label: 'Large Snakelike Corn Rows' },
    { img: MockImg, label: 'Small Snakelike Corn Rows' },
    { img: MockImg, label: 'Side Swirl Corn Rows' },
    { img: MockImg, label: 'Flat Top' },
    { img: MockImg, label: 'Front Crown Long Back' },
    { img: MockImg, label: 'Shaved Sided Slicked Back' },
    { img: MockImg, label: 'Side Parted Shaved Sides' },
    { img: MockImg, label: 'Mohawk' },
    { img: MockImg, label: 'Messy Long Back' },
    { img: MockImg, label: 'Center Parted Bob' },
    { img: MockImg, label: 'Buzz Cut' },
    { img: MockImg, label: 'Faux Hawk' },
    { img: MockImg, label: 'Shaved Sides Slicked Back' },
    { img: MockImg, label: 'Raised Front Same Length' },
    { img: MockImg, label: 'Col De Sacs and Long Back' },
    { img: MockImg, label: 'Close Shave and Loose Mohawk' },
    { img: MockImg, label: 'Ponytail' },
    { img: MockImg, label: 'Corn Rows' },
    { img: MockImg, label: 'Slicked Back Curly Back' },
    { img: MockImg, label: 'Slicked Back' },
    { img: MockImg, label: 'Spiked' },
    { img: MockImg, label: 'Short Bowl Cut' },
    { img: MockImg, label: 'Messy Long Length' },
    { img: MockImg, label: 'Dreads' },
    { img: MockImg, label: 'Straight Long Length' },
    { img: MockImg, label: 'Curly Long' },
    { img: MockImg, label: 'Straight Long Partial Messy' },
    { img: MockImg, label: 'Side Part Front Short' },
    { img: MockImg, label: 'Slicked Back Short' },
    { img: MockImg, label: 'Side Part Front Long' },
    { img: MockImg, label: 'Razer Side Part Slick' },
    { img: MockImg, label: 'Mullet' },
    { img: MockImg, label: 'Corn Rows' },
    { img: MockImg, label: 'Starfish Corn Rows' },
    { img: MockImg, label: 'Zig Zag Corn Rows' },
    { img: MockImg, label: 'Large Snakelike Corn Rows' },
    { img: MockImg, label: 'Small Snakelike Corn Rows' },
    { img: MockImg, label: 'Side Swirl Corn Rows' },
    { img: MockImg, label: 'Flat Top' },
    { img: MockImg, label: 'Front Crown Long Back' },
    { img: MockImg, label: 'Shaved Sided Slicked Back' },
    { img: MockImg, label: 'Side Parted Shaved Sides' },
    { img: MockImg, label: 'Mohawk' },
    { img: MockImg, label: 'Messy Long Back' },
    { img: MockImg, label: 'Center Parted Bob' },
    { img: MockImg, label: 'Shaved Sides Flat Top' },
    { img: MockImg, label: 'Shaved Sides Short Top' },
    { img: MockImg, label: 'Elvis' },
    { img: MockImg, label: 'Unknown' },
];
