export const maleHair = [
    'Close Shave',
    'Buzzcut',
    'Faux Hawk',
    'Shaved Sides Slicked Back',
    'Raised Front Same Length',
    'Col De Sacs and Long Back',
    'Close Shave and Loose Mohawk',
    'Ponytail',
    'Corn Rows',
    'Slicked Back Curly Back',
    'Slicked Back',
    'Spiked',
    'Short Bowl Cut',
    'Messy Long Length',
    'Dreads',
    'Straight Long Length',
    'Curly Long',
    'Straight Long Partial Messy',
    'Side Part Front Short',
    'Slicked Back Short',
    'Side Part Front Long',
    'Razer Side Part Slick',
    'Mullet',
    'Nightvision',
    'Corn Rows',
    'Starfish Corn Rows',
    'Zig Zag Corn Rows',
    'Large Snakelike Corn Rows',
    'Small Snakelike Corn Rows',
    'Side Swirl Corn Rows',
    'Flat Top',
    'Front Crown Long Back',
    'Shaved Sided Slicked Back',
    'Side Parted Shaved Sides',
    'Mohawk',
    'Messy Long Back',
    'Center Parted Bob',
    'Buzz Cut',
    'Faux Hawk',
    'Shaved Sides Slicked Back',
    'Raised Front Same Length',
    'Col De Sacs and Long Back',
    'Close Shave and Loose Mohawk',
    'Ponytail',
    'Corn Rows',
    'Slicked Back Curly Back',
    'Slicked Back',
    'Spiked',
    'Short Bowl Cut',
    'Messy Long Length',
    'Dreads',
    'Straight Long Length',
    'Curly Long',
    'Straight Long Partial Messy',
    'Side Part Front Short',
    'Slicked Back Short',
    'Side Part Front Long',
    'Razer Side Part Slick',
    'Mullet',
    'Corn Rows',
    'Starfish Corn Rows',
    'Zig Zag Corn Rows',
    'Large Snakelike Corn Rows',
    'Small Snakelike Corn Rows',
    'Side Swirl Corn Rows',
    'Flat Top',
    'Front Crown Long Back',
    'Shaved Sided Slicked Back',
    'Side Parted Shaved Sides',
    'Mohawk',
    'Messy Long Back',
    'Center Parted Bob',
    'Shaved Sides Flat Top',
    'Shaved Sides Short Top',
    'Elvis',
];
