export const hairColors = [
    'Black',
    'Dark Gray',
    'Medium Gray',
    'Darkest Brown',
    'Dark Brown',
    'Brown',
    'Light Brown',
    'Lighter Brown',
    'Lightest Brown',
    'Faded Brown',
    'Faded Blonde',
    'Lightest Blonde',
    'Lighter Blonde',
    'Light Blonde',
    'White Blonde',
    'Grayish Brown',
    'Redish Brown',
    'Red Brown',
    'Dark Red',
    'Red',
    'Very Red',
    'Vibrant Red',
    'Orangeish Red',
    'Faded Red',
    'Faded Orange',
    'Gray',
    'Light Gray',
    'Lighter Gray',
    'Lightest Gray',
    'Dark Purple',
    'Purple',
    'Light Purple',
    'Violet',
    'Vibrant Violet',
    'Candy Pink',
    'Light Pink',
    'Cyan',
    'Blue',
    'Dark Blue',
    'Green',
    'Emerald',
    'Oil Slick',
    'Shiney Green',
    'Vibrant Green',
    'Green',
    'Bleach Blonde',
    'Golden Blonde',
    'Orange Blonde',
    'Orange',
    'Vibrant Orange',
    'Shiny Orange',
    'Dark Orange',
    'Red',
    'Dark Red',
    'Very Dark Red',
    'Black',
    'Black',
    'Black',
    'Black',
    'Black',
];
